### ISSUE TITLE
Autocomplete / Async Retrieval for regionClsList

### ISSUE THREAD

**Issue by stajahlee** [waoai/react-image-annotate#38] opened 2020-04-01 20:41 UTC
I need to do something like:
```
<ReactImageAnnotate
    .......
    .......
    regionClsList={input => this.getClasses(input)}
/>
```
where given the input typed into the select 'value container' I can perform an api call filtered on the input (our potential items that need to be available to that dropdown is a very, very large list)

Is this possible at the moment?

**Comment by seveibar** [comment] 2020-04-03 02:20
This isn't possible at the moment. But it's a good idea, so I'm guessing you have a really big list of classes?

**Comment by stajahlee** [comment] 2020-04-03 02:33
@seveibar yes - we have over 33K devices to filter down from with an api call

**Comment by seveibar** [comment] 2020-04-03 06:34
I think you might be interested in what @ThibautGeriz is working on here: https://github.com/waoai/react-image-annotate/pull/32

Basically you could have a custom form with autocomplete. If it works for you, I can probably accelerate the merging process on that PR. Let me know

**Comment by stajahlee** [comment] 2020-04-03 13:43
That's awesome - I will pull it down and try this out today to see if we can work with this. I see that you merged the branch (but not released just yet) - that's fantastic. Thanks for letting me know!  I'll keep an eye out on the released build too to see if I can install from npm. :)

**Comment by seveibar** [comment] 2020-04-04 17:21
Hey @stajahlee, I've merged the `RegionEditLabel` override into `react-image-annotate` and published it after some fixes. You can try it out in version `0.2.5`.

Here's an example that produces the following screenshots (also can be seen in src/Annotator/index.story.js)

```javascript
const MyComponent = () => {
    const images = [
      exampleImage,
      "https://loremflickr.com/100/100/cars?lock=1",
      "https://loremflickr.com/100/100/cars?lock=2"
    ]

    const NewRegionEditLabel = ({
      region,
      editing,
      onDelete,
      onChange,
      onClose,
      onOpen
    }) => {
      return (
        <div style={{ backgroundColor: "white" }}>
          I'm the closed part
          <div style={{ display: editing ? "block" : "none" }}>
            I'm the part that shows when it's being edited!
            <button onClick={() => onDelete(region)}>Delete This Region</button>
            <button
              onClick={() => onChange({ ...region, cls: "awesome-value" })}
            >
              Set Classification to "awesome-value"
            </button>
            <button onClick={() => onClose(region)}>Close the edit mode</button>
          </div>
        </div>
      )
    }

    return (
      <Annotator
        onExit={actionAddon("onExit")}
        labelImages
        selectedImage={images[0]}
        RegionEditLabel={NewRegionEditLabel}
        images={[
          {
            src: exampleImage,
            name: "Seve's Desk"
          },
          {
            src: images[1],
            name: "Frame 0036"
          },
          {
            src: images[2],
            name: "Frame 0037"
          }
        ]}
      />
    )
}
```

![DeepinScreenshot_select-area_20200404131642](https://user-images.githubusercontent.com/1910070/78457235-c0bc3600-7676-11ea-932d-fdb8838305d9.png)

**Comment by stajahlee** [comment] 2020-04-07 22:35
@seveibar Thank you so much for releasing this - it is exactly what we need for this concern and my api call is working swimmingly. Unfortunately I have a new error when clicking the Settings button (in the Header). It crashes the application with the error: 
```
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```
I can make a new issue for this unless it is existing behavior you are aware of (for my case I really would love to just have all of the Header Buttons be optional with a prop to the Annotate component like you have for enabledTools. We don't really need to allow our users to have these additional settings or fullscreen option.

**Comment by seveibar** [comment] 2020-04-07 22:42
Let's split this into two issues, both of which can be solved:

1. Optional Header Buttons <- Want to make it :)?
2. Issue w/ Settings button (see below)

Now there are a couple reasons why the error in (2) might be happening. Keep in mind, it doesn't seem to reproduce on the demo playground. To fix this I'd need a sample github repository that shows the issue (that should then be posted as a new issue). I'm hoping you have two versions of react. Run `npm ls react` and see if any of the versions don't match. If they don't match, the fix is usually just updating react or using "resolutions" if you have yarn.

**Comment by stajahlee** [comment] 2020-04-07 22:44
I do see 
```
├── react@16.12.0 
└─┬ react-image-annotate@0.2.5
  └─┬ material-survey@1.0.34
    └── react@16.13.1 
```
when I run this command.

**Comment by stajahlee** [comment] 2020-04-07 22:47
As for the 
1. Optional Header Buttons
Yes that seems like something I would be able to work on and contribute. :)

**Comment by seveibar** [comment] 2020-04-07 23:19
I'll add some contributing/development info on the wiki tonight :) Yes the main way to run the test the library is with `yarn storybook` (it runs react storybook). It lets you put in different states of the component and see how they look in a browser.

**Comment by seveibar** [comment] 2020-04-07 23:19
Ill close this issue because we solved the original problem, but feel free to open new ones for problems or feature proposals :)

**Comment by stajahlee** [comment] 2020-04-07 23:20
Thank you so much for everything! It really is awesome.

**Closed** 2020-04-07 23:19 UTC
